"""
Export service for generating refined contracts (NOT review reports).
Uses contract refinement service to create improved contracts.
"""

import logging
from pathlib import Path
from datetime import datetime
from docx import Document
from docx.shared import RGBColor, Pt, Inches
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY

logger = logging.getLogger(__name__)


class ExportService:
    """Service for exporting refined contracts to various formats."""
    
    def generate_refined_contract_docx(
        self,
        refined_contract: str,
        safety_score: int,
        review_id: str,
        output_path: str
    ) -> str:
        """
        Generate a Word document with the refined/improved contract.
        
        Args:
            refined_contract: LLM-generated improved contract text
            safety_score: Original safety score
            review_id: Review ID for reference
            output_path: Path to save the DOCX file
        
        Returns:
            Path to generated file
        """
        try:
            doc = Document()
            
            # Title
            title = doc.add_heading('Refined Employment Contract', 0)
            title.alignment = 1  # Center
            
            # Metadata
            meta_para = doc.add_paragraph()
            meta_para.add_run(f'Original Safety Score: {safety_score}/100\n').italic = True
            meta_para.add_run(f'Review ID: {review_id}\n').italic = True
            meta_para.add_run(f'Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}\n').italic = True
            meta_para.alignment = 1
            
            doc.add_paragraph('_' * 80)
            doc.add_paragraph()
            
            # Info box
            info_para = doc.add_paragraph()
            info_run = info_para.add_run(
                '📝 This is a refined version of your contract with all recommended improvements applied. '
                'Critical issues have been fixed, missing clauses have been added, and negotiable points have been improved.'
            )
            info_run.font.color.rgb = RGBColor(0, 100, 200)
            info_run.italic = True
            
            doc.add_paragraph()
            doc.add_heading('IMPROVED CONTRACT', level=1)
            doc.add_paragraph()
            
            # Add refined contract text with proper formatting
            paragraphs = refined_contract.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    # Check if it's a heading (all caps or starts with number)
                    if para.strip().isupper() and len(para.strip()) < 100:
                        doc.add_heading(para.strip(), level=2)
                    elif para.strip()[0].isdigit() and '.' in para[:5]:
                        # Numbered section
                        doc.add_paragraph(para.strip(), style='List Number')
                    else:
                        doc.add_paragraph(para.strip())
            
            # Footer
            doc.add_page_break()
            footer = doc.add_paragraph()
            footer.add_run('Legal Disclaimer\n').bold = True
            footer.add_run(
                'This refined contract is generated by AI based on legal analysis. '
                'It is provided for reference and improvement purposes only. '
                'Please have this reviewed by a qualified attorney before signing.'
            ).italic = True
            
            # Save
            doc.save(output_path)
            logger.info(f"✅ Generated refined contract DOCX: {output_path}")
            return output_path
            
        except Exception as e:
            logger.error(f"Failed to generate refined contract DOCX: {e}")
            raise
    
    def generate_refined_contract_pdf(
        self,
        refined_contract: str,
        safety_score: int,
        review_id: str,
        output_path: str
    ) -> str:
        """
        Generate a PDF with the refined/improved contract.
        
        Args:
            refined_contract: LLM-generated improved contract text
            safety_score: Original safety score
            review_id: Review ID for reference
            output_path: Path to save the PDF file
        
        Returns:
            Path to generated file
        """
        try:
            doc = SimpleDocTemplate(
                output_path,
                pagesize=letter,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=50
            )
            
            # Container for the 'Flowable' objects
            elements = []
            
            # Define styles
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=22,
                textColor=colors.HexColor('#1f4788'),
                spaceAfter=20,
                alignment=TA_CENTER
            )
            
            body_style = ParagraphStyle(
                'CustomBody',
                parent=styles['Normal'],
                fontSize=11,
                alignment=TA_JUSTIFY,
                spaceAfter=12,
                leading=16
            )
            
            # Title
            elements.append(Paragraph("Refined Employment Contract", title_style))
            elements.append(Spacer(1, 12))
            
            # Metadata
            meta_text = f'''
            <i>
            Original Safety Score: {safety_score}/100<br/>
            Review ID: {review_id}<br/>
            Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}
            </i>
            '''
            elements.append(Paragraph(meta_text, styles['Normal']))
            elements.append(Spacer(1, 20))
            
            # Info box
            info_text = '''
            <para align=center>
            <font color="#0064c8"><i>
            📝 This is a refined version of your contract with all recommended improvements applied.<br/>
            Critical issues have been fixed, missing clauses have been added, and negotiable points have been improved.
            </i></font>
            </para>
            '''
            elements.append(Paragraph(info_text, styles['Normal']))
            elements.append(Spacer(1, 20))
            
            # Contract heading
            elements.append(Paragraph("<b>IMPROVED CONTRACT</b>", styles['Heading2']))
            elements.append(Spacer(1, 12))
            
            # Add refined contract content
            paragraphs = refined_contract.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    # Simple formatting
                    if para.strip().isupper() and len(para.strip()) < 100:
                        # Heading
                        elements.append(Paragraph(f"<b>{para.strip()}</b>", styles['Heading3']))
                    else:
                        # Normal paragraph
                        elements.append(Paragraph(para.strip(), body_style))
            
            # Footer disclaimer
            elements.append(Spacer(1, 30))
            elements.append(PageBreak())
            disclaimer_title = Paragraph("<b>Legal Disclaimer</b>", styles['Heading3'])
            disclaimer_text = Paragraph(
                '<i>This refined contract is generated by AI based on legal analysis. '
                'It is provided for reference and improvement purposes only. '
                'Please have this reviewed by a qualified attorney before signing.</i>',
                styles['Normal']
            )
            elements.append(disclaimer_title)
            elements.append(Spacer(1, 6))
            elements.append(disclaimer_text)
            
            # Build PDF
            doc.build(elements)
            logger.info(f"✅ Generated refined contract PDF: {output_path}")
            return output_path
            
        except Exception as e:
            logger.error(f"Failed to generate refined contract PDF: {e}")
            raise


# Global instance
export_service = ExportService()
